### ISSUE TITLE
ContentExport form loads blank and throws exception that ZipArchive doesn't exist in the namespace

### ISSUE THREAD

**Issue by vrkmajeti** [estockwell-alpert/ContentExportTool#7]
After installing Content export v8.9 in Sitecore 8.2 Update-7 website with .net 4.6.1, Content export form loads blank and shows following error.

Exception: System.Web.HttpCompileException
Message: e:\Websites\unwCommsDev\Website\sitecore\shell\Applications\ContentExport\ContentExport.aspx.cs(4438): error CS0234: The type or namespace name 'ZipArchive' does not exist in the namespace 'System.IO.Compression' (are you missing an assembly reference?)
Source: System.Web
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
   at System.Web.Compilation.BuildManager.CreateInstanceFromVirtualPath(VirtualPath virtualPath, Type requiredBaseType, HttpContext context, Boolean allowCrossApp)
   at System.Web.UI.PageHandlerFactory.GetHandlerHelper(HttpContext context, String requestType, VirtualPath virtualPath, String physicalPath)
   at Sitecore.DependencyInjection.AutowiredPageHandlerFactory.GetHandler(HttpContext context, String requestType, String url, String pathTranslated)
   at System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
![ContentExport form](https://user-images.githubusercontent.com/1881988/218006474-8ede8208-3830-4588-bc57-e3ec130af23b.PNG)

**Comment by kellyjjrusk** [comment]
I am having the same issue, specifically:

Upon loading the 9.2 installer on a PaaS CMS/Sitecore 10.2, I get the following error:

Compiler Error Message: CS1069: The type name 'ZipArchive' could not be found in the namespace 'System.IO.Compression'. This type has been forwarded to assembly 'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' Consider adding a reference to that assembly.

Is this an issue with it being 10.2?

**Comment by estockwell-alpert** [comment]
Are you using the version that includes the MediaExport? This is a known issue:

In order for the Media Export to work (see previous release), you must have System.IO.Compression installed in your solution. If you do not, the module will fail to compile. Either install System.IO.Compression, or install the NoMediaExport version of the package below

**Comment by kellyjjrusk** [comment]
Thanks Erica. I used the 9.2 for Azure installation as I am running 10.2 in an App Service and missed that it has an non media export version. I will upload that.

Regards,

Kelly

**Comment by kellyjjrusk** [comment]
@vrkmajeti I would look at installing the following version unless you want to follow the comments above from @estockwell-alpert where it is stated "you must have System.IO.Compression installed in your solution. If you do not, the module will fail to compile. Either install System.IO.Compression, or install the NoMediaExport version of the package"

To that end, I suspect you need to use the following package if you are not enabling System.IO.Compression: Content Export Tool v8.8.zip

**Comment by estockwell-alpert** [comment]
Thanks @kellyjjrusk 

To note, the [first release of Content Export Tool for Azure](https://github.com/estockwell-alpert/ContentExportTool/releases/tag/Azure) has a separate version for Media Export and No Media Export. **All later releases do NOT include the media export**

**Comment by kellyjjrusk** [comment]
Thank you @estockwell-alpert
